# ******** Mend Unified CLI Template for Github Actions ********
#
# You may wish to alter this file to override the build tool and Mend scanning technologies.
#
# For more configuration options, please check the technical documentation portal:
# ðŸ“š https://docs.mend.io/bundle/integrations/page/scan_with_the_mend_cli.html
#
# ******** Description ********
# mend dep will automatically use package managers and file system scanning to detect open source components.
# mend code will automatically detect languages and frameworks used in your projects to scan for code weaknesses.

# If you are NOT using a service user, and have multiple organizations, don't forget to call the scope -s parameter to set the organization

name: Mend CLI Scan

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
        MEND_URL: https://saas.whitesourcesoftware.com
      run: |
        echo "Downloading Mend CLI"
        curl -sSL https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend
        chmod +x /usr/local/bin/mend

        echo "Running Mend dependencies scan"
        mend dep -u --format sarif --export-results mend-dep-results.sarif

        echo "Running Mend code scan"
        mend code --format sarif --export-results mend-code-results.sarif

    - name: Upload SARIF results for dependency scan
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: mend-dep-results.sarif

    - name: Upload SARIF results for code scan
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: mend-code-results.sarif

